### ISSUE TITLE
Issue 5-Dickson

### ISSUE THREAD

**Issue by dmwambua** [promoteglobal/Mixed_Messages#19]

**Comment by promoteglobal** [comment]
Hi Dickson,

I deleted the other issues and kept this one so you only have 1 issue.  I've pushed the updated divs to the repo.  You can now add your code to `<div id="dickson5"></div>`.  

Thanks,
Katherine

**Comment by dmwambua** [comment]
I submitted a pull request with my changes.
Happy new year!
